import 'package:flutter/foundation.dart';

enum CountryField {
  FLAG,
  DIAL,
  NAME,
  CODE,
}

class Country {
  const Country({
    @required this.code,
    @required this.dial,
    @required this.flag,
    @required this.name,
  })  : assert(code != null),
        assert(dial != null),
        assert(flag != null),
        assert(name != null);

  final String code;
  final String dial;
  final String flag;
  final String name;

  String getField(CountryField field) {
    switch (field) {
      case CountryField.CODE:
        return code;
      case CountryField.DIAL:
        return dial;
      case CountryField.FLAG:
        return flag;
      case CountryField.NAME:
        return name;
      default:
        return '';
    }
  }
}

class Countries {

  final jsonCountries = const [
    {"name": "Andorra","dial": "376","code": "AD","flag": "🇦🇩"},
    {"name": "United Arab Emirates","dial": "971","code": "AE","flag": "🇦🇪"},
    {"name": "Afghanistan","dial": "93","code": "AF","flag": "🇦🇫"},
    {"name": "Antigua & Barbuda","dial": "1268","code": "AG","flag": "🇦🇬"},
    {"name": "Anguilla","dial": "1264","code": "AI","flag": "🇦🇮"},
    {"name": "Albania","dial": "355","code": "AL","flag": "🇦🇱"},
    {"name": "Armenia","dial": "374","code": "AM","flag": "🇦🇲"},
    {"name": "Angola","dial": "244","code": "AO","flag": "🇦🇴"},
    {"name": "Antarctica","dial": "672","code": "AQ","flag": "🇦🇶"},
    {"name": "Argentina","dial": "54","code": "AR","flag": "🇦🇷"},
    {"name": "American Samoa","dial": "1684","code": "AS","flag": "🇦🇸"},
    {"name": "Austria","dial": "43","code": "AT","flag": "🇦🇹"},
    {"name": "Australia","dial": "61","code": "AU","flag": "🇦🇺"},
    {"name": "Aruba","dial": "297","code": "AW","flag": "🇦🇼"},
    {"name": "Åland Islands","dial": "358","code": "AX","flag": "🇦🇽"},
    {"name": "Azerbaijan","dial": "994","code": "AZ","flag": "🇦🇿"},
    {"name": "Bosnia & Herzegovina","dial": "387","code": "BA","flag": "🇧🇦"},
    {"name": "Barbados","dial": "1246","code": "BB","flag": "🇧🇧"},
    {"name": "Bangladesh","dial": "880","code": "BD","flag": "🇧🇩"},
    {"name": "Belgium","dial": "32","code": "BE","flag": "🇧🇪"},
    {"name": "Burkina Faso","dial": "226","code": "BF","flag": "🇧🇫"},
    {"name": "Bulgaria","dial": "359","code": "BG","flag": "🇧🇬"},
    {"name": "Bahrain","dial": "973","code": "BH","flag": "🇧🇭"},
    {"name": "Burundi","dial": "257","code": "BI","flag": "🇧🇮"},
    {"name": "Benin","dial": "229","code": "BJ","flag": "🇧🇯"},
    {"name": "St. Barthélemy","dial": "590","code": "BL","flag": "🇧🇱"},
    {"name": "Bermuda","dial": "1441","code": "BM","flag": "🇧🇲"},
    {"name": "Brunei","dial": "673","code": "BN","flag": "🇧🇳"},
    {"name": "Bolivia","dial": "591","code": "BO","flag": "🇧🇴"},
    {"name": "Netherlands Antilles","dial": "599","code": "AN","flag": "🇧🇶"},
    {"name": "Brazil","dial": "55","code": "BR","flag": "🇧🇷"},
    {"name": "Bahamas","dial": "1242","code": "BS","flag": "🇧🇸"},
    {"name": "Bhutan","dial": "975","code": "BT","flag": "🇧🇹"},
    {"name": "Bouvet Island","dial": "47","code": "BV","flag": "🇧🇻"},
    {"name": "Botswana","dial": "267","code": "BW","flag": "🇧🇼"},
    {"name": "Belarus","dial": "375","code": "BY","flag": "🇧🇾"},
    {"name": "Belize","dial": "501","code": "BZ","flag": "🇧🇿"},
    {"name": "Canada","dial": "1","code": "CA","flag": "🇨🇦"},
    {"name": "Cocos (Keeling) Islands","dial": "61","code": "CC","flag": "🇨🇨"},
    {"name": "Congo - Kinshasa","dial": "243","code": "CD","flag": "🇨🇩"},
    {"name": "Central African Republic","dial": "236","code": "CF","flag": "🇨🇫"},
    {"name": "Congo - Brazzaville","dial": "242","code": "CG","flag": "🇨🇬"},
    {"name": "Switzerland","dial": "41","code": "CH","flag": "🇨🇭"},
    {"name": "Côte d’Ivoire","dial": "225","code": "CI","flag": "🇨🇮"},
    {"name": "Cook Islands","dial": "682","code": "CK","flag": "🇨🇰"},
    {"name": "Chile","dial": "56","code": "CL","flag": "🇨🇱"},
    {"name": "Cameroon","dial": "237","code": "CM","flag": "🇨🇲"},
    {"name": "China","dial": "86","code": "CN","flag": "🇨🇳"},
    {"name": "Colombia","dial": "57","code": "CO","flag": "🇨🇴"},
    {"name": "Costa Rica","dial": "506","code": "CR","flag": "🇨🇷"},
    {"name": "Cuba","dial": "53","code": "CU","flag": "🇨🇺"},
    {"name": "Cape Verde","dial": "238","code": "CV","flag": "🇨🇻"},
    {"name": "Christmas Island","dial": "61","code": "CX","flag": "🇨🇽"},
    {"name": "Cyprus","dial": "357","code": "CY","flag": "🇨🇾"},
    {"name": "Czechia","dial": "420","code": "CZ","flag": "🇨🇿"},
    {"name": "Germany","dial": "49","code": "DE","flag": "🇩🇪"},
    {"name": "Djibouti","dial": "253","code": "DJ","flag": "🇩🇯"},
    {"name": "Denmark","dial": "45","code": "DK","flag": "🇩🇰"},
    {"name": "Dominica","dial": "1767","code": "DM","flag": "🇩🇲"},
    {"name": "Dominican Republic","dial": "1849","code": "DO","flag": "🇩🇴"},
    {"name": "Algeria","dial": "213","code": "DZ","flag": "🇩🇿"},
    {"name": "Ecuador","dial": "593","code": "EC","flag": "🇪🇨"},
    {"name": "Estonia","dial": "372","code": "EE","flag": "🇪🇪"},
    {"name": "Egypt","dial": "20","code": "EG","flag": "🇪🇬"},
    {"name": "Eritrea","dial": "291","code": "ER","flag": "🇪🇷"},
    {"name": "Spain","dial": "34","code": "ES","flag": "🇪🇸"},
    {"name": "Ethiopia","dial": "251","code": "ET","flag": "🇪🇹"},
    {"name": "Finland","dial": "358","code": "FI","flag": "🇫🇮"},
    {"name": "Fiji","dial": "679","code": "FJ","flag": "🇫🇯"},
    {"name": "Falkland Islands","dial": "500","code": "FK","flag": "🇫🇰"},
    {"name": "Micronesia","dial": "691","code": "FM","flag": "🇫🇲"},
    {"name": "Faroe Islands","dial": "298","code": "FO","flag": "🇫🇴"},
    {"name": "France","dial": "33","code": "FR","flag": "🇫🇷"},
    {"name": "Gabon","dial": "241","code": "GA","flag": "🇬🇦"},
    {"name": "United Kingdom","dial": "44","code": "GB","flag": "🇬🇧"},
    {"name": "Grenada","dial": "1473","code": "GD","flag": "🇬🇩"},
    {"name": "Georgia","dial": "995","code": "GE","flag": "🇬🇪"},
    {"name": "French Guiana","dial": "594","code": "GF","flag": "🇬🇫"},
    {"name": "Guernsey","dial": "44","code": "GG","flag": "🇬🇬"},
    {"name": "Ghana","dial": "233","code": "GH","flag": "🇬🇭"},
    {"name": "Gibraltar","dial": "350","code": "GI","flag": "🇬🇮"},
    {"name": "Greenland","dial": "299","code": "GL","flag": "🇬🇱"},
    {"name": "Gambia","dial": "220","code": "GM","flag": "🇬🇲"},
    {"name": "Guinea","dial": "224","code": "GN","flag": "🇬🇳"},
    {"name": "Guadeloupe","dial": "590","code": "GP","flag": "🇬🇵"},
    {"name": "Equatorial Guinea","dial": "240","code": "GQ","flag": "🇬🇶"},
    {"name": "Greece","dial": "30","code": "GR","flag": "🇬🇷"},
    {"name": "South Georgia & South Sandwich Islands","dial": "500","code": "GS","flag": "🇬🇸"},
    {"name": "Guatemala","dial": "502","code": "GT","flag": "🇬🇹"},
    {"name": "Guam","dial": "1671","code": "GU","flag": "🇬🇺"},
    {"name": "Guinea-Bissau","dial": "245","code": "GW","flag": "🇬🇼"},
    {"name": "Guyana","dial": "592","code": "GY","flag": "🇬🇾"},
    {"name": "Hong Kong SAR China","dial": "852","code": "HK","flag": "🇭🇰"},
    {"name": "Heard & McDonald Islands","dial": "0","code": "HM","flag": "🇭🇲"},
    {"name": "Honduras","dial": "504","code": "HN","flag": "🇭🇳"},
    {"name": "Croatia","dial": "385","code": "HR","flag": "🇭🇷"},
    {"name": "Haiti","dial": "509","code": "HT","flag": "🇭🇹"},
    {"name": "Hungary","dial": "36","code": "HU","flag": "🇭🇺"},
    {"name": "Indonesia","dial": "62","code": "ID","flag": "🇮🇩"},
    {"name": "Ireland","dial": "353","code": "IE","flag": "🇮🇪"},
    {"name": "Israel","dial": "972","code": "IL","flag": "🇮🇱"},
    {"name": "Isle of Man","dial": "44","code": "IM","flag": "🇮🇲"},
    {"name": "India","dial": "91","code": "IN","flag": "🇮🇳"},
    {"name": "British Indian Ocean Territory","dial": "246","code": "IO","flag": "🇮🇴"},
    {"name": "Iraq","dial": "964","code": "IQ","flag": "🇮🇶"},
    {"name": "Iran","dial": "98","code": "IR","flag": "🇮🇷"},
    {"name": "Iceland","dial": "354","code": "IS","flag": "🇮🇸"},
    {"name": "Italy","dial": "39","code": "IT","flag": "🇮🇹"},
    {"name": "Jersey","dial": "44","code": "JE","flag": "🇯🇪"},
    {"name": "Jamaica","dial": "1876","code": "JM","flag": "🇯🇲"},
    {"name": "Jordan","dial": "962","code": "JO","flag": "🇯🇴"},
    {"name": "Japan","dial": "81","code": "JP","flag": "🇯🇵"},
    {"name": "Kenya","dial": "254","code": "KE","flag": "🇰🇪"},
    {"name": "Kyrgyzstan","dial": "996","code": "KG","flag": "🇰🇬"},
    {"name": "Cambodia","dial": "855","code": "KH","flag": "🇰🇭"},
    {"name": "Kiribati","dial": "686","code": "KI","flag": "🇰🇮"},
    {"name": "Comoros","dial": "269","code": "KM","flag": "🇰🇲"},
    {"name": "St. Kitts & Nevis","dial": "1869","code": "KN","flag": "🇰🇳"},
    {"name": "North Korea","dial": "850","code": "KP","flag": "🇰🇵"},
    {"name": "South Korea","dial": "82","code": "KR","flag": "🇰🇷"},
    {"name": "Kuwait","dial": "965","code": "KW","flag": "🇰🇼"},
    {"name": "Cayman Islands","dial": " 345","code": "KY","flag": "🇰🇾"},
    {"name": "Kazakhstan","dial": "7","code": "KZ","flag": "🇰🇿"},
    {"name": "Laos","dial": "856","code": "LA","flag": "🇱🇦"},
    {"name": "Lebanon","dial": "961","code": "LB","flag": "🇱🇧"},
    {"name": "St. Lucia","dial": "1758","code": "LC","flag": "🇱🇨"},
    {"name": "Liechtenstein","dial": "423","code": "LI","flag": "🇱🇮"},
    {"name": "Sri Lanka","dial": "94","code": "LK","flag": "🇱🇰"},
    {"name": "Liberia","dial": "231","code": "LR","flag": "🇱🇷"},
    {"name": "Lesotho","dial": "266","code": "LS","flag": "🇱🇸"},
    {"name": "Lithuania","dial": "370","code": "LT","flag": "🇱🇹"},
    {"name": "Luxembourg","dial": "352","code": "LU","flag": "🇱🇺"},
    {"name": "Latvia","dial": "371","code": "LV","flag": "🇱🇻"},
    {"name": "Libya","dial": "218","code": "LY","flag": "🇱🇾"},
    {"name": "Morocco","dial": "212","code": "MA","flag": "🇲🇦"},
    {"name": "Monaco","dial": "377","code": "MC","flag": "🇲🇨"},
    {"name": "Moldova","dial": "373","code": "MD","flag": "🇲🇩"},
    {"name": "Montenegro","dial": "382","code": "ME","flag": "🇲🇪"},
    {"name": "St. Martin","dial": "590","code": "MF","flag": "🇲🇫"},
    {"name": "Madagascar","dial": "261","code": "MG","flag": "🇲🇬"},
    {"name": "Marshall Islands","dial": "692","code": "MH","flag": "🇲🇭"},
    {"name": "North Macedonia","dial": "389","code": "MK","flag": "🇲🇰"},
    {"name": "Mali","dial": "223","code": "ML","flag": "🇲🇱"},
    {"name": "Myanmar (Burma)","dial": "95","code": "MM","flag": "🇲🇲"},
    {"name": "Mongolia","dial": "976","code": "MN","flag": "🇲🇳"},
    {"name": "Northern Mariana Islands","dial": "1670","code": "MP","flag": "🇲🇵"},
    {"name": "Martinique","dial": "596","code": "MQ","flag": "🇲🇶"},
    {"name": "Mauritania","dial": "222","code": "MR","flag": "🇲🇷"},
    {"name": "Montserrat","dial": "1664","code": "MS","flag": "🇲🇸"},
    {"name": "Malta","dial": "356","code": "MT","flag": "🇲🇹"},
    {"name": "Mauritius","dial": "230","code": "MU","flag": "🇲🇺"},
    {"name": "Maldives","dial": "960","code": "MV","flag": "🇲🇻"},
    {"name": "Malawi","dial": "265","code": "MW","flag": "🇲🇼"},
    {"name": "Mexico","dial": "52","code": "MX","flag": "🇲🇽"},
    {"name": "Malaysia","dial": "60","code": "MY","flag": "🇲🇾"},
    {"name": "Mozambique","dial": "258","code": "MZ","flag": "🇲🇿"},
    {"name": "Namibia","dial": "264","code": "NA","flag": "🇳🇦"},
    {"name": "New Caledonia","dial": "687","code": "NC","flag": "🇳🇨"},
    {"name": "Niger","dial": "227","code": "NE","flag": "🇳🇪"},
    {"name": "Norfolk Island","dial": "672","code": "NF","flag": "🇳🇫"},
    {"name": "Nigeria","dial": "234","code": "NG","flag": "🇳🇬"},
    {"name": "Nicaragua","dial": "505","code": "NI","flag": "🇳🇮"},
    {"name": "Netherlands","dial": "31","code": "NL","flag": "🇳🇱"},
    {"name": "Norway","dial": "47","code": "NO","flag": "🇳🇴"},
    {"name": "Nepal","dial": "977","code": "NP","flag": "🇳🇵"},
    {"name": "Nauru","dial": "674","code": "NR","flag": "🇳🇷"},
    {"name": "Niue","dial": "683","code": "NU","flag": "🇳🇺"},
    {"name": "New Zealand","dial": "64","code": "NZ","flag": "🇳🇿"},
    {"name": "Oman","dial": "968","code": "OM","flag": "🇴🇲"},
    {"name": "Panama","dial": "507","code": "PA","flag": "🇵🇦"},
    {"name": "Peru","dial": "51","code": "PE","flag": "🇵🇪"},
    {"name": "French Polynesia","dial": "689","code": "PF","flag": "🇵🇫"},
    {"name": "Papua New Guinea","dial": "675","code": "PG","flag": "🇵🇬"},
    {"name": "Philippines","dial": "63","code": "PH","flag": "🇵🇭"},
    {"name": "Pakistan","dial": "92","code": "PK","flag": "🇵🇰"},
    {"name": "Poland","dial": "48","code": "PL","flag": "🇵🇱"},
    {"name": "St. Pierre & Miquelon","dial": "508","code": "PM","flag": "🇵🇲"},
    {"name": "Pitcairn Islands","dial": "64","code": "PN","flag": "🇵🇳"},
    {"name": "Puerto Rico","dial": "1939","code": "PR","flag": "🇵🇷"},
    {"name": "Palestinian Territories","dial": "970","code": "PS","flag": "🇵🇸"},
    {"name": "Portugal","dial": "351","code": "PT","flag": "🇵🇹"},
    {"name": "Palau","dial": "680","code": "PW","flag": "🇵🇼"},
    {"name": "Paraguay","dial": "595","code": "PY","flag": "🇵🇾"},
    {"name": "Qatar","dial": "974","code": "QA","flag": "🇶🇦"},
    {"name": "Réunion","dial": "262","code": "RE","flag": "🇷🇪"},
    {"name": "Romania","dial": "40","code": "RO","flag": "🇷🇴"},
    {"name": "Serbia","dial": "381","code": "RS","flag": "🇷🇸"},
    {"name": "Russia","dial": "7","code": "RU","flag": "🇷🇺"},
    {"name": "Rwanda","dial": "250","code": "RW","flag": "🇷🇼"},
    {"name": "Saudi Arabia","dial": "966","code": "SA","flag": "🇸🇦"},
    {"name": "Solomon Islands","dial": "677","code": "SB","flag": "🇸🇧"},
    {"name": "Seychelles","dial": "248","code": "SC","flag": "🇸🇨"},
    {"name": "Sudan","dial": "249","code": "SD","flag": "🇸🇩"},
    {"name": "Sweden","dial": "46","code": "SE","flag": "🇸🇪"},
    {"name": "Singapore","dial": "65","code": "SG","flag": "🇸🇬"},
    {"name": "St. Helena","dial": "290","code": "SH","flag": "🇸🇭"},
    {"name": "Slovenia","dial": "386","code": "SI","flag": "🇸🇮"},
    {"name": "Svalbard & Jan Mayen","dial": "47","code": "SJ","flag": "🇸🇯"},
    {"name": "Slovakia","dial": "421","code": "SK","flag": "🇸🇰"},
    {"name": "Sierra Leone","dial": "232","code": "SL","flag": "🇸🇱"},
    {"name": "San Marino","dial": "378","code": "SM","flag": "🇸🇲"},
    {"name": "Senegal","dial": "221","code": "SN","flag": "🇸🇳"},
    {"name": "Somalia","dial": "252","code": "SO","flag": "🇸🇴"},
    {"name": "Suriname","dial": "597","code": "SR","flag": "🇸🇷"},
    {"name": "South Sudan","dial": "211","code": "SS","flag": "🇸🇸"},
    {"name": "São Tomé & Príncipe","dial": "239","code": "ST","flag": "🇸🇹"},
    {"name": "El Salvador","dial": "503","code": "SV","flag": "🇸🇻"},
    {"name": "Syria","dial": "963","code": "SY","flag": "🇸🇾"},
    {"name": "Swaziland","dial": "268","code": "SZ","flag": "🇸🇿"},
    {"name": "Turks & Caicos Islands","dial": "1649","code": "TC","flag": "🇹🇨"},
    {"name": "Chad","dial": "235","code": "TD","flag": "🇹🇩"},
    {"name": "French Southern Territories","dial": "262","code": "TF","flag": "🇹🇫"},
    {"name": "Togo","dial": "228","code": "TG","flag": "🇹🇬"},
    {"name": "Thailand","dial": "66","code": "TH","flag": "🇹🇭"},
    {"name": "Tajikistan","dial": "992","code": "TJ","flag": "🇹🇯"},
    {"name": "Tokelau","dial": "690","code": "TK","flag": "🇹🇰"},
    {"name": "Timor-Leste","dial": "670","code": "TL","flag": "🇹🇱"},
    {"name": "Turkmenistan","dial": "993","code": "TM","flag": "🇹🇲"},
    {"name": "Tunisia","dial": "216","code": "TN","flag": "🇹🇳"},
    {"name": "Tonga","dial": "676","code": "TO","flag": "🇹🇴"},
    {"name": "Turkey","dial": "90","code": "TR","flag": "🇹🇷"},
    {"name": "Trinidad & Tobago","dial": "1868","code": "TT","flag": "🇹🇹"},
    {"name": "Tuvalu","dial": "688","code": "TV","flag": "🇹🇻"},
    {"name": "Taiwan","dial": "886","code": "TW","flag": "🇹🇼"},
    {"name": "Tanzania","dial": "255","code": "TZ","flag": "🇹🇿"},
    {"name": "Ukraine","dial": "380","code": "UA","flag": "🇺🇦"},
    {"name": "Uganda","dial": "256","code": "UG","flag": "🇺🇬"},
    {"name": "United States","dial": "1","code": "US","flag": "🇺🇸"},
    {"name": "Uruguay","dial": "598","code": "UY","flag": "🇺🇾"},
    {"name": "Uzbekistan","dial": "998","code": "UZ","flag": "🇺🇿"},
    {"name": "Vatican City","dial": "379","code": "VA","flag": "🇻🇦"},
    {"name": "St. Vincent & Grenadines","dial": "1784","code": "VC","flag": "🇻🇨"},
    {"name": "Venezuela","dial": "58","code": "VE","flag": "🇻🇪"},
    {"name": "British Virgin Islands","dial": "1284","code": "VG","flag": "🇻🇬"},
    {"name": "U.S. Virgin Islands","dial": "1340","code": "VI","flag": "🇻🇮"},
    {"name": "Vietnam","dial": "84","code": "VN","flag": "🇻🇳"},
    {"name": "Vanuatu","dial": "678","code": "VU","flag": "🇻🇺"},
    {"name": "Wallis & Futuna","dial": "681","code": "WF","flag": "🇼🇫"},
    {"name": "Samoa","dial": "685","code": "WS","flag": "🇼🇸"},
    {"name": "Kosovo","dial": "383","code": "XK","flag": "🇽🇰"},
    {"name": "Yemen","dial": "967","code": "YE","flag": "🇾🇪"},
    {"name": "Mayotte","dial": "262","code": "YT","flag": "🇾🇹"},
    {"name": "South Africa","dial": "27","code": "ZA","flag": "🇿🇦"},
    {"name": "Zambia","dial": "260","code": "ZM","flag": "🇿🇲"},
    {"name": "Zimbabwe","dial": "263","code": "ZW","flag": "🇿🇼"}
  ];

  List<Country> countries = [];

  Countries() {
    for (int i = 0; i < jsonCountries.length; ++i) {
      final country = jsonCountries[i];
      countries.add(
        Country(
          dial: country['dial'], 
          flag: country['flag'],
          name: country['name'],
          code: country['code'],
        )
      );
    }

  }
  List<Country> get list => countries;

  Country getBy({
    @required CountryField field,
    @required String value,
  }) {
    return countries.firstWhere(
      (country) => country.getField(field) == value,
      orElse: () => null,
    );
  }
}
